"""Self-contained HTML report from temp/misalign_v2/{summary.json,subjects_v3.csv,slices_v3.csv,figs/,slabs/}.
Every number here is read from summary.json (written by analyze.py) — nothing is typed in by hand."""
import base64, json, os, html, numpy as np, pandas as pd
ROOT = "/home/minsukc/vggt"; OUT = f"{ROOT}/temp/misalign_v2"; FIG = f"{OUT}/figs"; SL = f"{OUT}/slabs"
S = json.load(open(f"{OUT}/summary.json")); sub = pd.read_csv(f"{OUT}/subjects_v3.csv", index_col=0)
def img(name, w="100%", d=FIG):
    return f'<img src="data:image/png;base64,{base64.b64encode(open(f"{d}/{name}","rb").read()).decode()}" style="max-width:{w};border:1px solid #ddd">'
def tbl(d, fmt="{:.2f}"):
    h = "<table><tr>" + "".join(f"<th>{html.escape(str(c))}</th>" for c in [d.index.name or ""] + list(d.columns)) + "</tr>"
    for i, r in d.iterrows():
        h += "<tr><td>" + html.escape(str(i)) + "</td>" + "".join(f"<td>{fmt.format(v) if isinstance(v, float) else v}</td>" for v in r) + "</tr>"
    return h + "</table>"
pct = lambda x: f"{100*x:.1f}%"
P = S["prior"]; T = S["tiers"]; sens = S["sens_subj_gt5"]; il = S["interleave"]; hk = S["spike_slices_gt5"]; R = S["rules"]; V = S.get("vs_v3"); BC = S["band_counts"]; SN = S["spike_needed"]
# tables
t_slice = pd.DataFrame({"slices with spike >": [pct(S["slice_frac_spike_gt"][k]) for k in ("3", "5", "8")],
                        "adjacent pairs with step >": [pct(S["pair_frac_step_gt"][k]) for k in ("3", "5", "8")]}, index=["3 mm", "5 mm", "8 mm"]).T
t_subj = pd.DataFrame({f">{k} mm": [pct(S["subj_frac_spike_gt"][k]), pct(S["subj_frac_step_gt"][k]), pct(S["subj_frac_sev_gt"][k])] for k in ("3", "4", "5", "8", "10")},
                      index=["spike only (single-slice slips)", "step only (adjacent-pair discontinuity)", "severity = max(spike, step)  ← headline"])
if V: t_subj.loc["severity, previous sweep (v3, 20 mm window, zeroed direction-disagreements)"] = [pct(V["prev_subj_frac_sev_gt"][k]) for k in ("3", "4", "5", "8", "10")]
src = pd.DataFrame(S["per_source"]).T; src.index.name = "source"
cent = pd.read_csv(f"{OUT}/per_centre_v3.csv", index_col=0)
t_sens = pd.DataFrame({"subjects >5 mm": [pct(v) for v in sens.values()]}, index=list(sens.keys()))
t_tier = pd.DataFrame([dict(tier=k, threshold_mm=v["thr"], train=f'{v["train_kept"]}/{v["train_kept"]+v["train_dropped"]}', val=f'{v["val_kept"]}/{v["val_kept"]+v["val_dropped"]}', test=f'{v["test_kept"]}/{v["test_kept"]+v["test_dropped"]}',
                            train_kept_pct=pct(v["train_kept"] / (v["train_kept"] + v["train_dropped"])), valtest_kept_pct=pct((v["val_kept"] + v["test_kept"]) / (v["val_kept"] + v["val_dropped"] + v["test_kept"] + v["test_dropped"])),
                            centres_with_zero_left=sum(1 for a, b in v["per_centre"].values() if a > 0 and b == 0), valtest_centres_with_zero_left=sum(1 for a, b in v["per_centre_valtest"].values() if a > 0 and b == 0)) for k, v in T.items()]).set_index("tier")
pc = pd.DataFrame({k: {c: f"{b}/{a}" for c, (a, b) in v["per_centre"].items()} for k, v in T.items()}); pc.index.name = "centre/vendor group, all sections (kept/total)"
pcv = pd.DataFrame({k: {c: f"{b}/{a}" for c, (a, b) in v["per_centre_valtest"].items()} for k, v in T.items()})
vt_tot = {c: a for c, (a, b) in T["sev8"]["per_centre_valtest"].items()}; vt_keep = {c: b for c, (a, b) in T["sev8"]["per_centre_valtest"].items()}
pcv["share before (sev8)"] = [pct(vt_tot[c] / sum(vt_tot.values())) for c in pcv.index]; pcv["share after (sev8)"] = [pct(vt_keep[c] / sum(vt_keep.values())) for c in pcv.index]
pcv.index.name = "val+test centre/vendor group (kept/total)"
t_rules = pd.DataFrame({"count": [R["spike_seg_fallback_slices"], R["step_seg_fallback_pairs"], R["step_both_large_pairs"], R["step_contradict_pairs_seg_gt5"], R["step_contradict_pairs"], R["subj_with_any_fallback"], R["subj_with_both_large"]]},
                       index=["slices scored from segmentation alone (registration pinned at the 40 mm bound)", "pairs scored from segmentation alone (same)", "pairs kept at min(seg,img) despite direction disagreement (both ≥8 mm)",
                              "pairs zeroed: seg claims >5 mm, image (valid) contradicts", "pairs zeroed: any direction disagreement incl. sub-threshold", "subjects with any seg-only value", "subjects with a both-large pair"])
if V:
    t_trans = pd.DataFrame({"subjects": V["transitions"]}); t_trans.index.name = "previous band → new band"
def sev(rel): return float(sub.loc[rel].severity)
def verdict(k): return "CLEAN (≤3 mm)" if k <= 3 else "MILD (3–5 mm) — keep" if k <= 5 else "MODERATE (5–8 mm)" if k <= 8 else "SEVERE (>8 mm)"
ex = ["MNMs_sax/MNMs_F6J9L9", "CMRxRecon2025/Cine_combined/CMRx25_R2test_Center012_Philips_30T_IngeniaCX_P008", "CMRxRecon2024/Cine_combined/CMRx24_Train_P025",
      "MNMs_sax/MNMs_D8E4F4", "CMRxRecon2025/Cine_combined/CMRx25_R1val_Center001_UIH_30T_umr780_P007", "CMRxRecon2024/Cine_combined/CMRx24_Train_P001",
      "ACDC_sax/ACDC_patient034", "CMRxRecon2023/Cine_combined/CMRx23_Train_P068", "ACDC_sax/ACDC_patient081",
      "MNMs_sax/MNMs_G7S6V0", "CMRxRecon2025/Cine_combined/CMRx25_train_Center006_Siemens_30T_Prisma_P005", "CMRxRecon2024/Cine_combined/CMRx24_Train_P019", "MNMs_sax/MNMs_A1E9Q1"]
ex = sorted([r for r in ex if r in sub.index and os.path.exists(f"{SL}/{r.split('/')[-1]}.png")], key=sev)
gallery = "".join(f'<div class="ex"><div class="cap"><b>{verdict(sev(r))}</b> · {html.escape(r)} · severity <b>{sev(r):.1f} mm</b> (worst spike {sub.loc[r].max_spike:.1f}, worst step {sub.loc[r].max_step if np.isfinite(sub.loc[r].max_step) else float("nan"):.1f})</div>{img(r.split("/")[-1] + ".png", "100%", SL)}</div>' for r in ex)
v31 = ""
if V:
    v31 = f"""<div class="warn"><b>v3.1 (2026-09-11): two consensus-rule bugs fixed, full re-sweep.</b> A by-eye check of the <i>clean</i> gallery found <code>ACDC_patient081</code> (reported 2.4 mm) with an obvious ~28 mm jump between z7 and z8. Cause: the NCC registration searched only ±20 mm, so the true match was outside the window; the peak sat pinned at the bound, was discarded as degenerate, and the "both estimators must agree" rule then threw away the segmentation's correct 28 mm answer as if the image had said "no shift". Fixes: (1) search window 20→40 mm, and a registration pinned at the bound now means "offset ≥ window" — the segmentation value is used as-is (marked † in the galleries; {R["spike_seg_fallback_slices"]} slices, {R["step_seg_fallback_pairs"]} pairs); a flat/featureless registration is still "no answer". (2) The step direction check zeroed pairs whose two vectors pointed apart even when both were large (e.g. CMRx25 Center001 UIH P003 z1: seg 20.2 / img 15.2 mm → 0.0); pairs with both estimates ≥8 mm now keep the conservative min(seg, img) ({R["step_both_large_pairs"]} pairs), while a disagreement with one small estimate is still zeroed as the segmentation false positive it usually is (where the segmentation claims >5 mm and the image, with a valid answer, does not back it: {R["step_contradict_pairs_seg_gt5"]} pairs, {pct(R["step_contradict_frac_of_seg_gt5"])} of such seg-flagged pairs — the reason the rule exists; {R["step_contradict_pairs"]} pairs in total counting sub-threshold disagreements that cannot change a band). A fault-injection test (<code>tools/misalign_v2/test_fault_injection.py</code>, 16 checks: in-window 5.4/−2.8 mm slip, a 28 mm slip under both the 20 and 40 mm windows, an 8.1 mm 3-slice block, and synthetic direction disagreements) now covers exactly this gap. Effect: <b>{V["n_band_changed"]} of {S["n_measurable"]} subjects changed band ({V["n_moved_up"]} up, {V["n_moved_down"]} down; {V["moved_up_from_clean"]} left "clean", {V["moved_up_to_severe"]} became "severe")</b>; the >5 mm subject rate moved {pct(V["prev_subj_frac_sev_gt"]["5"])} → {pct(S["subj_frac_sev_gt"]["5"])} and >8 mm {pct(V["prev_subj_frac_sev_gt"]["8"])} → {pct(S["subj_frac_sev_gt"]["8"])}. "Kink" was renamed "spike" (single-slice deviation) to pair with "step" (adjacent-pair jump); same formula. Is spike still needed next to step? {SN["n_band_differs_step_only"]} subjects would land in a different band with step alone, so yes.</div>
<h3>What the fixes changed</h3><div class="row"><div>{tbl(t_rules, "{}")}</div><div>{tbl(t_trans, "{}")}<p style="font-size:12px">Per-subject list: <code>temp/misalign_v2/band_changes_vs_v3.csv</code>; the biggest movers are shown at the bottom of <code>95c_misalignment_examples_by_category.html</code>.</p></div></div>"""
H = f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>Inter-slice misalignment in the pooled SAX cohort: re-analysis (v3.1, reviewed)</title>
<style>body{{font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;max-width:1400px;margin:30px auto;padding:0 20px;line-height:1.45;color:#222}}
table{{border-collapse:collapse;font-size:13px;margin:8px 0}}th,td{{border:1px solid #ccc;padding:3px 8px;text-align:right}}th{{background:#f3f3f3}}td:first-child,th:first-child{{text-align:left}}
.tldr{{background:#eef6ee;border-left:5px solid #4c9f70;padding:10px 16px}}.warn{{background:#fff4e5;border-left:5px solid #e08a3c;padding:10px 16px;margin-top:12px}}
.ex{{margin:14px 0}}.cap{{font-size:13px;margin-bottom:4px}}code{{background:#f4f4f4;padding:1px 4px}}h2{{border-bottom:1px solid #ddd;margin-top:36px}}.row{{display:flex;gap:16px;flex-wrap:wrap}}.row>div{{flex:1;min-width:380px}}</style></head><body>
<h1>Inter-slice breath-hold misalignment in the pooled SAX training cohort — independent re-analysis</h1>
<p><i>2026-09-05, revised after a 2-reviewer adversarial check and a full rerun; v3.1 2026-09-11 after a by-eye catch and two rule fixes · all {S["n_subjects"]} pooled subjects (train+val+test), all 12 phases · read-only on <code>scratch/data/</code>; outputs under <code>temp/misalign_v2/</code>, code in <code>tools/misalign_v2/</code></i></p>
<div class="tldr"><b>TL;DR.</b> Real inter-slice in-plane misalignment exists in every source and centre, but the data is not badly corrupted: the <b>median slice offset is {S["spike_quantiles"]["p50"]:.1f} mm</b> (≈1 pixel), <b>{pct(S["pair_frac_step_gt"]["5"])} of adjacent slice pairs have a discontinuity >5 mm</b>, and <b>{pct(S["subj_frac_sev_gt"]["5"])} of subjects have at least one >5 mm discontinuity</b> ({pct(S["subj_frac_sev_gt"]["8"])} >8 mm, {pct(S["subj_frac_sev_gt"]["3"])} >3 mm). The measurement uses two independent estimators that must agree (segmentation-centroid geometry and NCC image registration), each taken as the median over 12 cardiac phases; offsets are phase-invariant, i.e. a per-slice breath-hold property. docs/94's "65.6% misaligned at 4 mm" is overstated but not absurd: like-for-like (its own interior-slice column vs our severity at its 4 mm threshold) it is {pct(P["flag_rate_interior"])} vs {pct(P["ours_sev_gt4"])}; its metric additionally flags {pct(P["prior_flagged_but_sev_le3"])} of subjects that have no discontinuity above 3 mm, mostly from polynomial-fit residual and tiny apical/basal masks. <b>Curation:</b> a subject-level severity cut (<code>curated_sev8mm.txt</code>: {T["sev8"]["train_kept"]}/{T["sev8"]["train_kept"]+T["sev8"]["train_dropped"]} train kept; <code>curated_sev5mm.txt</code>: {T["sev5"]["train_kept"]}) keeps every train centre/vendor group; slice-level masking is <i>not</i> recommended (block shifts have no single "bad slice", and neighbours of a slip inherit half its spike). The docs/38 gate on an ablation remains the arbiter of whether any of this matters for reconstruction. <b>Every measurable subject is rendered</b> as a no-gap, no-interpolation stacked-band reslice with the epicardial extent ticked per slice (and the real LAX frames where the source has them) in one gallery per severity band: <code>_html/95d_gallery_clean.html</code> ({BC["clean"]}), <code>_html/95d_gallery_mild.html</code> ({BC["mild"]}), <code>_html/95d_gallery_moderate.html</code> ({BC["moderate"]}), <code>_html/95d_gallery_severe.html</code> ({BC["severe"]}). A curated version with 4 examples per band spanning each band's range, plus the subjects the v3.1 fixes reclassified, is at <code>_html/95c_misalignment_examples_by_category.html</code> — start there.</div>
{v31}
<div class="warn"><b>What changed vs the first version of this report (prove-it review).</b> (1) The spike metric halves a shifted <i>block</i> of slices, so a "step" detector between adjacent slices was added; the headline subject rate at >5 mm moved from {pct(sens["consensus_min"])} (spike only) to {pct(S["subj_frac_sev_gt"]["5"])} (spike or step). (2) The "~half of severe cases are interleaved zig-zag" claim was withdrawn: a lone slip produces the (−s/2, +s, −s/2) alternation by construction; requiring a ≥4-slice alternating run gives {pct(il["frac_run_ge4"])} of severe subjects. (3) The comparison with docs/94 is now like-for-like (interior slices both sides). (4) The recommended slice-mask list was withdrawn ({hk["halo"]} of {hk["total"]} slices >5 mm are the half-magnitude halo of a bigger neighbour). (5) Image-registration sign convention fixed and degenerate registrations (flat ROI) dropped; unmeasurable subjects are now named explicitly in each curated list's header instead of being silently kept.</div>

<h2>1. Method</h2>
<p>For every slice z of every subject (all 12 phases; <code>tools/misalign_v2/metric_v2.py</code>):</p>
<ul><li><b>Segmentation estimator</b>: epicardial (LV+MYO, Task114 nnU-Net) centroid per slice and phase. <i>Spike</i> = <code>c_z − (c_{{z−1}} + c_{{z+1}})/2</code>; <i>step</i> = <code>(c_{{z+1}} − c_z) − median_z(c_{{z+1}} − c_z)</code> (the subject's own smooth drift removed). A smooth LV long axis gives ≈0 for both (a 5 mm spike at 10 mm pitch would need a 10 mm radius of curvature); a slice or block acquired in a different breath-hold gives its in-plane offset. Median vector over the 12 phases; the RMS scatter of the 12 vectors is the cross-phase noise.</li>
<li><b>Image estimator</b>: NCC translation registration (±40 mm, sub-pixel) of slice z to z−1 and z+1 inside the dilated heart ROI, same spike/step algebra on the registered displacements. Independent of the segmentation. Sign convention and window coverage verified by fault injection (<code>test_fault_injection.py</code>: a +5.4/−2.8 mm slip, a 28 mm slip, an 8.1 mm 3-slice block, all recovered to within 1–2 mm by both estimators; the 28 mm slip under a 20 mm window is recovered through the pinned-registration fallback).</li>
<li><b>Consensus</b>: a slice/pair is measurable when the epicardial mask is ≥400 mm², ≥6 phases contribute and both registrations have NCC ≥0.4 ({S["n_spike_slices"]} slices, {S["n_step_pairs"]} pairs); its value is min(seg, img), i.e. both must show it. A registration pinned at its search bound counts as "≥40 mm" (the segmentation value is used); a flat registration is "no answer" (unscored). A step whose two vectors disagree in direction keeps min(seg, img) if both are ≥8 mm and is zeroed otherwise. Subject <b>severity</b> = max over its measurable slices/pairs of max(spike, step); {S["n_measurable"]} of {S["n_subjects"]} subjects are measurable.</li></ul>
<div class="row"><div>{img("F1_seg_vs_img.png")}<p style="font-size:12px">Independent estimators agree: r={S["r_seg_img_spike"]:.2f} over all consensus slices ({S["r_seg_img_spike_clip15"]:.2f} with both clipped at 15 mm), r={S["r_seg_img_spike_mid"]:.2f} on mid-ventricular slices with NCC>0.6; median vector disagreement {S["spike_agree_median_mm"]:.1f} mm (spike), {S["step_agree_median_mm"]:.1f} mm (step). The wider 40 mm window admits more spurious far NCC peaks ({S["img_spurious_far_slices"]} consensus slices with image >10 mm but segmentation <3 mm, vs 26 at 20 mm), which lowers r but not the scores: min(seg, img) takes the segmentation's small value there.</p></div>
<div>{img("F4_phase_consistency.png")}<p style="font-size:12px">All 12 phases of one slice give the same offset vector: median cross-phase scatter {S["xphase_noise_seg_med"]:.2f} mm (seg) / {S["xphase_noise_img_med"]:.2f} mm (img); on flagged (>5 mm) slices {S["xphase_noise_seg_flagged"]:.2f} / {S["xphase_noise_img_flagged"]:.2f} mm, and {pct(S["frac_flagged_noise_gt_spike"])} of flagged slices have scatter larger than their offset. The offset is a per-slice breath-hold property, not segmentation noise.</p></div></div>

<h2>2. Results</h2>
<div class="row"><div><h3>Per slice / per adjacent pair</h3>{tbl(t_slice, "{}")}<p style="font-size:12px">Slice spike quantiles: p50 {S["spike_quantiles"]["p50"]:.1f}, p75 {S["spike_quantiles"]["p75"]:.1f}, p90 {S["spike_quantiles"]["p90"]:.1f}, p95 {S["spike_quantiles"]["p95"]:.1f}, p99 {S["spike_quantiles"]["p99"]:.1f} mm.</p></div>
<div><h3>Per subject ({S["n_measurable"]} measurable)</h3>{tbl(t_subj, "{}")}<p style="font-size:12px">Severity quantiles: p25 {S["subj_sev_quantiles"]["p25"]:.1f}, p50 {S["subj_sev_quantiles"]["p50"]:.1f}, p75 {S["subj_sev_quantiles"]["p75"]:.1f}, p90 {S["subj_sev_quantiles"]["p90"]:.1f}, p95 {S["subj_sev_quantiles"]["p95"]:.1f} mm.</p></div></div>
{img("F2_subject_cdf.png", "900px")}
<h3>Sensitivity of the >5 mm subject rate to the estimator choice (same gated slices, same denominator)</h3>{tbl(t_sens, "{}")}
<h3>Per source</h3>{tbl(src)}
<h3>Per centre / vendor (the diversity view)</h3>
<p>Every centre/vendor group with ≥5 measurable subjects has subjects above 5 mm ({S["n_centres_ge5"]} groups; the statement is {"true" if S["centres_all_affected_gt5"] else "false"}) and every group keeps a substantial usable majority at an 8 mm cut. Differences between centres are real (MNMs centre 1 Siemens and several CMRx25 UIH scanners worst; Fudan Vida and the CMRx25 Siemens sites cleanest) but this is a property of clinical breath-hold cine everywhere, not of one bad source.</p>
{img("F3_per_centre.png", "900px")}{tbl(cent)}
<h3>Pattern</h3><p>Among the {il["n_severe"]} subjects with severity >5 mm, {pct(il["frac_run_ge4"])} show an alternating-sign spike over ≥4 consecutive slices (the interleaved odd/even two-breath-hold signature) and {pct(il["frac_run_ge5"])} over ≥5; the majority are isolated slips or a shifted block (e.g. the basal group in <code>MNMs_G7S6V0</code>). Of the {hk["total"]} slices with spike >5 mm, {hk["local_max"]} are local maxima and {hk["halo"]} are the half-magnitude halo of a bigger neighbour.</p>

<h2>3. docs/94 revisited</h2>
<p>docs/94 computed the centroid of the <i>union</i> LV+MYO+RV per slice, fit a robust polynomial across z, and flagged the maximum residual >4 mm (65.6% of train subjects). Three things inflate that: the whole-heart centroid moves by a third of the heart width where the RV tapers in/out; the most apical/basal slices have tiny unstable masks and dominate the max; and a polynomial residual over 9–16 points carries the fit's own error. Like-for-like on the train split (n={P["n"]}; its interior-slice column vs our severity): docs/94 flags {pct(P["flag_rate_interior"])} at 4 mm, we find {pct(P["ours_sev_gt4"])} above 4 mm and {pct(P["ours_sev_gt3"])} above 3 mm; r={P["r_interior_vs_sev"]:.2f}. Of the subjects docs/94 flags, {pct(P["prior_flagged_but_sev_le3"])} have no discontinuity above 3 mm and {pct(P["prior_flagged_but_sev_le5"])} none above 5 mm; conversely {pct(P["sev_gt5_but_prior_clean"])} of our >5 mm subjects it called clean. So the disagreement is mostly the 4 mm threshold (≈3 pixels, borrowed from a different metric) plus end-slice noise, not a wholesale error — but "the median subject is misaligned" does not survive: the median subject's worst discontinuity is {S["subj_sev_quantiles"]["p50"]:.1f} mm.</p>
{img("F5_prior_vs_ours.png", "460px")}

<h2>4. What counts as corrupted vs clean — examples</h2>
<p>Each panel: coronal and sagittal cuts through the LV centre with every native SAX slice stacked as an equal-height band, no gap, no interpolation (yellow ticks = epicardial extent per slice; red ▶ = consensus spike >5 mm; † in the number column = segmentation-only value, registration beyond its window), real LAX frames beside CMRx23/24 panels for reference. A clean stack has a continuous epicardial border; a corrupted one has a staircase. Sorted by severity; <code>ACDC_patient081</code> is the subject whose miss triggered v3.1.</p>
<p><b>Rule:</b> a discontinuity counts when both estimators put it above 5 mm (the simulated respiratory AP shift in training is 4–9 mm, so smaller GT offsets are below the noise the model already absorbs; 5 mm ≈ 3–4 pixels ≈ half a myocardial wall). Subject tiers: clean ≤3 mm, mild 3–5 mm (keep), moderate 5–8 mm, severe >8 mm.</p>
{gallery}

<h2>5. Curation options that preserve centre diversity</h2>
{tbl(t_tier, "{}")}
<p><b>All three sections are curated</b> (train, val and test): the val/test GT carries the same corruption, and a misaligned GT penalises a correct reconstruction, so scoring against it is noise. Lists are in <code>pooled.txt</code> format, so <code>data.split_file</code> can point at them directly; {T["sev8"]["unmeasurable_kept"]} unmeasurable subject(s) — too few gated slices, mostly CMRx25 Siemens Aera/Sola with short stacks — are kept in every list, not judged, and named in each list's header. Per centre/vendor group, kept/total at each tier:</p>{tbl(pc, "{}")}
<p><b>Does curating val/test skew its centre composition?</b> No: at the 8 mm cut the per-centre share of val+test moves by under one point for every large group; the only groups that shrink noticeably are the ones worst at misalignment (MNMs centre 1 Siemens, CMRx25 Aera). The pre-existing weakness — most CMRx25 centres have only 1–7 val/test subjects before any cut — is a property of the original split, not of the curation, and would need a centre-stratified re-split (which costs comparability with every existing run) to fix.</p>{tbl(pcv, "{}")}
<p><b>Recommendation.</b></p><ol>
<li>Run the config-only ablation with <code>curated_sev8mm.txt</code> first (drops the clearly broken stacks only), then <code>curated_sev5mm.txt</code>; judge by docs/38. If the 5 mm arm wins despite ~{pct(T["sev5"]["train_dropped"]/(T["sev5"]["train_kept"]+T["sev5"]["train_dropped"]))} less data, the artefact is actively harmful; if 8 mm ≈ 5 mm ≈ baseline, the model is absorbing it and no curation is needed.</li>
<li>Do <b>not</b> mask individual slices: a block shift has no single wrong slice, and the neighbours of a slip inherit half its spike, so a slice list removes good slices and leaves blocks untouched. If per-subject exclusion costs too much data, the per-z-plane robust/heteroscedastic loss from docs/94 §5 Stage 1b is the right granularity.</li>
<li>Do not cut at 3 mm ({pct(S["subj_frac_sev_gt"]["3"])} of subjects) and do not re-register (docs/94 Stage 2): the offsets are in-plane translations of a few mm; exclusion or a robust loss is cheaper and reversible.</li></ol>

<h2>6. Caveats</h2>
<ul><li>Only <b>in-plane</b> offsets are measurable from a SAX stack; the through-plane (SI) component of a breath-hold difference is invisible here (LAX NIfTIs on disk carry no scanner geometry).</li>
<li>End slices and slices with a small epicardial mask (apex, base beyond the ventricles) are unscored; basal/apical slices with an image estimate but no segmentation show higher image-only rates, but that is exactly where NCC registration is unreliable, so they are not counted either way. Their loss weight was not measured.</li>
<li>By-eye audit after v3.1: a random 48 clean + 24 mild subjects were inspected as contact sheets — no missed jump. One weak spot: {R["subj_weak_step_evidence"]} subjects ({R["subj_weak_step_evidence_by_band"]["clean"]} clean, {R["subj_weak_step_evidence_by_band"]["mild"]} mild) have <i>every</i> scored pair zeroed as a seg/img contradiction, so their step score is uninformative and the severity rests on the spike consensus alone (column <code>weak_step_evidence</code> in <code>subjects_v3.csv</code>; flagged, not excluded).</li>
<li>Seg-only (†) values rest on one estimator; they are rare ({R["spike_seg_fallback_slices"]} slices, {R["step_seg_fallback_pairs"]} pairs) and only arise when the registration says the offset exceeds 40 mm, but they are not cross-checked.</li>
<li>Thresholds (3/5/8 mm) come from pixel size, wall thickness and the training respiratory simulation, not from a model ablation.</li></ul>
<h2>7. Artifacts</h2><ul><li><code>_html/95c_misalignment_examples_by_category.html</code> — 4 examples per severity band spanning its range + the subjects v3.1 reclassified (start here).</li><li><code>_html/95d_gallery_{{clean,mild,moderate,severe}}.html</code> — every measurable subject ({S["n_measurable"]} total), one gallery per band, slab reslices (<code>tools/misalign_v2/render_slab.py</code>, <code>build_band_gallery.py</code>; panels in <code>temp/misalign_v2/slabs/</code>).</li><li><code>_html/95b_misalignment_severe_gallery.html</code> — severe-only (>8 mm), an earlier layout, kept for compatibility (superseded by <code>95d_gallery_severe.html</code>, same content).</li><li><code>temp/misalign_v2/slices_v3.csv</code>, <code>steps_v3.csv</code>, <code>subjects_v3.csv</code>, <code>per_source_v3.csv</code>, <code>per_centre_v3.csv</code>, <code>band_changes_vs_v3.csv</code>, <code>summary.json</code>; previous sweep under <code>_v3_superseded/</code></li><li><code>temp/misalign_v2/curated_sev{{5,8,10}}mm.txt</code></li><li><code>tools/misalign_v2/</code>: <code>metric_v2.py</code> (sweep), <code>analyze.py</code> (all numbers + lists + figures), <code>test_fault_injection.py</code>, <code>render_slab.py</code>, <code>fig_phase.py</code>, <code>build_html.py</code></li></ul>
</body></html>"""
open(f"{ROOT}/_html/95_slice_misalignment_reanalysis.html", "w").write(H); print("html bytes", len(H))
